### ISSUE TITLE
error in step

### ISSUE THREAD

**Issue by emmannaemeka** [MariaNattestad/post-Assemblytics#2]
Hello
Please I ran into this error and don't seem to know what is wrong

bedtools getfasta -tab -name -bed  domenico.insertions_above_10bp.assembly_coordinates.slop10.bed -fi ~.genome_domenico.fasta -fo domenico.insertions_above_10bp.assembly_coordinates.slop10.sequences.tab

I get this error Error: malformed BED entry at line 21. Start Coordinate detected that is < 0. Exiting

What could be wrong

**Comment by MariaNattestad** [comment]
Like I responded in the last issue you posted, these are not well-tested scripts but just ideas for things you can try. The few lines of code I added here do not have a lot of value anymore, so I will archive this repo to avoid further confusion.
To answer your question, it says the bed file has a coordinate < 0, which would have happened because the previous step added a slop of 10 to a file that had a start coordinate < 10 in it.
